version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /home/ibhi/data/mongodb/db:/data/db
    ports:
      - "27017:27017"